server:
  port: 8081

spring:
  data:
    mongodb:
      #host: 34.205.100.14	
      host: 172.31.65.115
      port: 27017

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
     #defaultZone: http://localhost:8761/eureka/
     #defaultZone: http://54.235.23.223:8761/eureka/
      defaultZone: http://172.31.70.152:8761/eureka/
      
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
