server:
  port: 8081

spring:
 data:
    mongodb:
      host: http://172.31.64.17
      port: 27017

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://54.235.23.223:8761/eureka/
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
