server:
  port: 8082
  
spring:  
  data:
    mongodb:
      host: 34.205.100.14
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: 34.205.100.14:8761/eureka/
    healthcheck:
      enabled: true
    instance:
      preferIpAddress: true
      metadataMap.instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
