server:
  port: 8082
  
spring:  
  data:
    mongodb:
      host: 34.205.100.14
      port: 27017

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://54.235.23.223:8761/eureka/
  instance:
    preferIpAddress: true
